version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres-BDO
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    environment:
      POSTGRES_DB: warehouse 
      POSTGRES_PASSWORD: apiDBO
      POSTGRES_HOST_AUTH_METHOD: trust

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warehouse-api
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
